[vars]
DEV_DOCKER_CONF = "--env-file .env.dev -f configs/docker/docker-compose.yml -f configs/docker/docker-compose.dev.yml"

app_name = "shortener"

[tools]
go = '1.23'

[tasks.dev]
description = "Run dev environment"
run = "docker compose {{vars.DEV_DOCKER_CONF}} up"

[tasks.down]
description = "Stop and remove all dev containers"
run = "docker compose {{vars.DEV_DOCKER_CONF}} down"

[tasks.rebuild]
description = "Full rebuild with delete volumes"
run = [
  "docker compose {{vars.DEV_DOCKER_CONF}} down -v",
  "docker compose {{vars.DEV_DOCKER_CONF}} up --build --force-recreate",
]

[tasks.logs]
description = "Watch Docker logs"
run = "docker compose logs -f"

[tasks.test]
description = "Run tests inside container"
run = [
  "mise rebuild -- -d",
  "docker compose {{vars.DEV_DOCKER_CONF}} exec {{vars.app_name}} go test ./... --cover",
  "mise down"
]

[tasks.shell]
description = "Connect to shell"
run = "docker compose {{vars.DEV_DOCKER_CONF}} exec {{vars.app_name}} sh"

[tasks.redis]
description = "Connect to Redis"
run = "docker compose {{vars.DEV_DOCKER_CONF}} exec redis redis-cli"

[tasks.deps]
description = "Update dependencies"
run = "docker compose {{vars.DEV_DOCKER_CONF}} exec {{vars.app_name}} go mod download"

[tasks.build]
run = 'echo "running build tasks"'
