package web

import (
	"fmt"
	"log"
	"net/http"

	"github.com/sorokin-vladimir/shortener/internal/utils"
)

func handleError(err error, w http.ResponseWriter) {
	log.Println(err)
	var errString string

	switch err.Error() {
	case utils.RATE_LIMIT_EXCEEDED:
		errString = "Rate limit exceeded. Please try again later."
	case utils.INVALID_URL:
		errString = "Looks like the input string is not a valid URL. Please try again."
	case utils.INVALID_URL_TOO_SHORT:
		errString = "Input URL is too short to cut. Please provide a longer URL."
	case utils.INVALID_URL_LOCALHOST:
		errString = "URL cannot be shortened for 'localhost'. Please provide a valid URL."
	case utils.SHORT_EXISTS:
		errString = "The provided short is already exist. Please provide a different short URL or use autogenerated."
	case utils.INTERNAL_ERROR:
	default:
		errString = "Something went wrong. Please try again later."
	}

	fmt.Fprintf(w, `<span class="error">%s</span>`, errString)
}
