services:
  shortener:
    build:
      context: ../../
      dockerfile: configs/docker/Dockerfile.prod
    ports:
      - "80:8080"
      - "443:8080"
    environment:
      REDIS_URL: ${REDIS_URL}

volumes:
  redis_data:

networks:
  app_network:
