services:
  redis:
    ports:
      - "6379:6379"
    volumes:
      - ../../data:/data

  shortener:
    build:
      context: ../../
      dockerfile: configs/docker/Dockerfile.dev
    working_dir: /app
    volumes:
      - ../../:/app:cached
      - go_mod_cache:/go/pkg/mod

volumes:
  # redis_data:
  go_mod_cache:
