services:
  redis:
    ports:
      - "6379:6379"
    volumes:
      - ../../app/tmp:/data
      # - redis_data:/data

  shortener:
    build:
      context: ../../app/
      dockerfile: configs/docker/Dockerfile.dev
    working_dir: /app
    volumes:
      - ../../app:/app:cached
      - go_mod_cache:/go/pkg/mod

volumes:
  # redis_data:
  go_mod_cache:
