services:
  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ../../app/tmp:/data

  shortener:
    build:
      context: ../../app/
      dockerfile: configs/docker/Dockerfile.dev
    working_dir: /app
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ../../app:/app:cached
      - go_mod_cache:/go/pkg/mod

  client:
    build:
      context: ../../client/
      dockerfile: configs/docker/Dockerfile.dev
    volumes:
      - ../../client:/app:cached
      - /app/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}

  nginx:
    volumes:
      - ../../configs/nginx/nginx.templ.dev.conf:/etc/nginx/nginx.template.conf:ro
      - ../../configs/nginx/entrypoint.sh:/entrypoint.sh:ro
    ports:
      - ${PORT}:${PORT}
    entrypoint: ["/bin/sh", "/entrypoint.sh"]


volumes:
  go_mod_cache:
