# Stage 1: Build frontend
FROM node:22-alpine AS frontend
WORKDIR /app
COPY ./client .
RUN npm install && npm run build

# Stage 2: Build backend
FROM golang:1.23-alpine AS backend
WORKDIR /app
COPY ./app .
COPY --from=frontend /app/build ./static
RUN go build -o app main.go

# Stage 3: Nginx
FROM nginx:1.26.2-perl AS proxy
COPY ./configs/nginx/nginx.prod.conf /etc/nginx/nginx.conf
COPY --from=backend /app /app

CMD ["nginx", "-g", "daemon off;"]
