services:
  redis:
    image: redis:7
    networks:
      - app_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  shortener:
    build:
      context: ../../app/
      dockerfile: configs/docker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ""
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
      PORT: ${PORT}
      API_QUOTA: ${API_QUOTA}
      DOMAIN: ${DOMAIN}
      EXPIRY_HOURS: ${EXPIRY_HOURS}

  client:
    build:
      context: ../../client/
      dockerfile: configs/docker/Dockerfile
    # volumes:
    #   - ./client:/app:cached
    networks:
      - app_network
    # environment:
      # REACT_APP_API_URL: http://localhost:8080

  nginx:
    image: nginx:1.26.2-perl
    networks:
      - app_network
    depends_on:
      - client
      - shortener

volumes:
  redis_data:

networks:
  app_network:
