services:
  shortener:
    build:
      context: ../../app/
      dockerfile: configs/docker/Dockerfile.test
    command: ["go", "run", "main.go"]

  client:
    build:
      context: ../../client/
      dockerfile: configs/docker/Dockerfile.test
    command: ["npm", "run", "dev"]
