FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install golang.org/x/tools/cmd/cover@latest
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

EXPOSE 8080
