name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: go test ./... -v

      # - name: Build Docker Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: false
      #     tags: mydockerhubuser/myapp:latest

  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Push Docker Image
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: mydockerhubuser/myapp:latest

  #     - name: Deploy via SSH
  #       uses: appleboy/ssh-action@v0.1.8
  #       with:
  #         host: ${{ secrets.PROD_SERVER }}
  #         username: ${{ secrets.PROD_USER }}
  #         key: ${{ secrets.PROD_SSH_KEY }}
  #         script: |
  #           docker pull mydockerhubuser/myapp:latest
  #           docker stop myapp || true
  #           docker rm myapp || true
  #           docker run -d --name myapp --network app_network -p 8080:8080 mydockerhubuser/myapp:latest
